---
title: "Lab03"
author: "Amruth Karun M V"
date: "05/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r include=FALSE}
library(tidyverse)
install.packages("wordcloud2")
library(wordcloud2)
```

```{r echo=FALSE}
# Create Data
Prop <- c(3,7,9,5,4)
pie(Prop , labels = c("Gr-A","Gr-B","Gr-C","Gr-D","Gr-E"), col =rainbow(5))
pie(Prop , labels = c("Gr-A","Gr-B","Gr-C","Gr-D","Gr-E"), col =heat.colors(5))
```

```{r}
wordcloud2(data=demoFreq, size=.5)
```

```{r}
# The mtcars dataset:
data <- as.matrix(mtcars)
head(data)

# Default Heatmap
heatmap(data, scale="column", xlab="specifications",
         col = terrain.colors(256)) #normalized based on column values
```

```{r}
ggplot(mtcars, aes(x=as.factor(cyl), y=mpg)) +
geom_boxplot(fill="slateblue", alpha=0.2) +
xlab("cyl") + ggtitle("Box Plot Analysis of cyl/mpg")
```

```{r}
marks <- c(99,56,78,55.5,32,90,80,81,56,59,45,77,84.5,84,70,72,68,32,79,90)
```

```{r}
#basic scatterplot
ggplot(mtcars, aes(x=wt, y=qsec)) + geom_point()
ggplot(mtcars, aes(x=disp, y=wt))+ geom_point()
ggplot(mtcars, aes(x=mpg, y=hp))+ geom_point()
ggplot(mtcars, aes(x=mpg, y=disp))+ geom_point(col="blue")
```

```{r}
data <- data.frame( name=c(rep("A",500), rep("B",500), rep("B",500), rep("C",20), rep('D', 100)),
value=c( rnorm(500, 10, 5), rnorm(500, 13, 1), rnorm(500, 18, 1), rnorm(20, 25, 4), rnorm(100, 12, 1)))
ggplot(data, aes(x=name, y=value,fill=name)) +
geom_violin()
```

```{r}
ggplot(mtcars, aes(x=as.factor(cyl), y=mpg,fill=cyl)) + geom_violin()
```




